# Generated by Django 3.1 on 2020-08-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('dirName', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=1000, unique=True)),
                ('mapUrl', models.CharField(max_length=10000, unique=True)),
            ],
        ),
    ]
